server:
  port: 8087
eureka:
  client:
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
spring:
  application:
    name: auth-service
leyou:
  jwt:
    secret: leyou@Login(Auth}*^31)&heiMa% # 登录校验的密钥
    pubKeyPath: D:\studysofteware\key\rsa.pub # 公钥地址
    priKeyPath: D:\studysofteware\key\rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: LY_TOKEN
    CookieMaxAge: 1800

ribbon:
  ConnectTimeout=1000: