server:
  port: 8083
spring:
  application:
    name: leyou-search
  data:
    elasticsearch:
      cluster-nodes: 192.168.28.134:9300
      cluster-name: elasticsearch
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: non_null
eureka:
  client:
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10