server:
  port: 8081
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-expiration-duration-in-seconds: 15 #15秒不发送就过期
    lease-renewal-interval-in-seconds: 5 #5秒发送一次心跳

#配置mybatis
mybatis:
  type-aliases-package: leyou.com.item.pojo
#配置数据库
spring:
  application:
    name: item-service
  datasource:
    password: root
    url: jdbc:mysql://127.0.0.1:3306/leyou?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  rabbitmq:
    username: leyou
    password: leyou
    virtual-host: /leyou
    template:
      exchange: LEYOU.ITEM.EXCHANGE
      publisher-confirms: true
    host: 192.168.28.134