server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.28.134
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
leyou:
  jwt:
    pubKeyPath: D:\studysofteware\key\rsa.pub # 公钥地址
    cookieName: LY_TOKEN
