spring:
  thymeleaf:
    cache: false
  application:
    name: leyou-goods
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    username: leyou
    password: leyou
    virtual-host: /leyou
    template:
      exchange: LEYOU.ITEM.EXCHANGE
      publisher-confirms: true
    host: 192.168.28.134
eureka:
  client:
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
server:
  port: 8085
