
spring:
  thymeleaf:
    cache: false
  application:
    name: leyou-goods
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
server:
  port: 8085